<a href="https://colab.research.google.com/github/Rapid130RS/iris_dataset/blob/master/scikitlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
#this is to deomonstrate the use of Scikit learn in analysing a data set
#see <https://scikit-learn.org/stable/tutorial/basic/tutorial.html>

import numpy as np
import sklearn #import scikit learn
import pandas as pd # allows input/output of a CSV file and processing
#iris = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv') # I imported the data set from a URL due to the IDE that I use. 
from sklearn.datasets import load_iris  #Sklearn has the Iris dataset preloaded                                                                                               # Equally, I could use the dataset that I imported to this repo.
iris = load_iris()
# print (iris) #print output to see how the data is imported. I commneted this out as I only wanted to read the data and the structure of the array.
n_samples, n_features = iris.data.shape #the data the s_samples and n_features refer to the two demensional array. Numpy recognises the columns and rows in the array as features and samples respectively. 
# the iris data attribute is a numpy array
numberOfSamples = str(n_samples)
numberOfFeatures = str(n_features)
firstRecord = str(iris.data[0]) #iris.data; data is an attribute already defined in the dataset
nameOfClasses = str(iris.target_names[0]) #in the scikit iris dataset, target names is assigned in the array.
print ("Overview of the dataset:")
print ("The number of samples studied is: "+ numberOfSamples) # there are 150 samples
print ("The number of features (Petal and Sepel) is: "+ numberOfFeatures) # there are 4 colums
print ("The data for the first record is :"+ firstRecord)# this is the first sample in the dataset, the seple lenght is 5.1cm, width 3.5cm, Petal length is 1.4cm and width 0.2cm
print ("The first record refers to Sepel length as "+str(iris.data[0,0])+".cm, Seple width is "+str(iris.data[0,1])+".cm, Petel length is "+str(iris.data[0,2])+".cm and Petal width is "+str(iris.data[0,3])+ ".cm ")
print ("The three classes of flower studes are :"+ str(iris.target_names[0])+", "+str(iris.target_names[1])+" and "+str(iris.target_names[2])+".")# this outputs the values in the array for the 
# Having had a brief look at the date set, I want to look at what SchKit can do
X, y = iris.data, iris.target #define two variables. X is in caps as the data var is two dememensial, while y is lower case as is one demensiaonla
from sklearn.svm import LinearSVC #import linear support vector classifacaiton machine- a machine learning class that is used to conduct machine learning
#LinearSVC() #looking at the class and its attributes, commented out once reviewed
clf= LinearSVC(C=150,max_iter=10000) #create the classifer (clf) and asign the value c=150, which is the total number of samples. C need not be the number of samples.
clf = clf.fit(X,y) #this is the fit function, which is an intital step in creeating an machine learning environment. A convergence warning may appear here, depending on the version of python. It can be ignored.
print ("The process of trainng the model revises the array: "+ str(clf.coef_))
#print (clf.intercept_) 
# Having defined the model, it can be used to predict values
newSepelLength=float(input("Enter the length of the Sepel: "))
newSepelWidth=float(input("Enter the width of the Sepel: "))
newPetelLength=float(input("Enter the length of the Petel: "))
newPetelWidth=float(input("Enter the width of the Petel: "))
#dt = np.dtype(float)
newMeasurement=np.array([newSepelLength, newSepelWidth, newPetelLength, newPetelWidth])
arrayForTest=newMeasurement.reshape(-1,4)
print ("You entered: "+str(arrayForTest))
#[float(arrayForTest) for i in newMeasurement]
clf.predict(arrayForTest)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Overview of the dataset:
The number of samples studied is: 150
The number of features (Petal and Sepel) is: 4
The data for the first record is :[5.1 3.5 1.4 0.2]
The first record refers to Sepel length as 5.1.cm, Seple width is 3.5.cm, Petel length is 1.4.cm and Petal width is 0.2.cm 
The three classes of flower studes are :setosa, versicolor and virginica.
The process of trainng the model revises the array: [[ 0.30773208  0.43035635 -1.042325   -0.6167912 ]
 [-0.03533075 -0.98904515  0.58642333 -1.11572844]
 [-0.81448439 -1.66046511  2.43451032  4.38311463]]
Enter the length of the Sepel: 0.2
Enter the width of the Sepel: .3
Enter the length of the Petel: .4
Enter the width of the Petel: .5
You entered: [[0.2 0.3 0.4 0.5]]


array([1])